networks:
  default:
    external:
      name: traefik

services:
  groceryman:
    restart: unless-stopped
    container_name: groceryman
    build: .
    volumes:
      - ./data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.groceryman.rule=Host(`groceryman.skrattpotatis.dillerm.io`)
      - traefik.http.routers.groceryman.tls.certresolver=le
      - traefik.http.routers.groceryman.entrypoints=websecure
